// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzsckzebhcoeayobhglr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6c2NremViaGNvZWF5b2JoZ2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MDA3NjcsImV4cCI6MjA1MzM3Njc2N30.MDhg1SHg0Co74HjBvoHNYQw2LiaDupxSQNhsP9v-cz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);